version: "3.3"
services:
  db:
    image: postgres:14.2-alpine
    container_name: datasource
    environment:
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./src/main/resources/db/init:/docker-entrypoint-initdb.d