spring:
  output:
    ansi:
      enabled: always
  JPA:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc.time_zone: UTC
  flyway:
    enabled: false
  jooq:
    sql-dialect:Postgres


  datasource:
    url: jdbc:postgresql://localhost/app_db
    username: app_user
    password: password


server:
  port: 4000
  error:
    path: /api/error
    include-stacktrace: always


